# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('create_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('update_time', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('public_time', unixtimestampfield.fields.UnixTimeStampField(default=1493058114)),
                ('text', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_ext', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.SmallIntegerField(blank=True, null=True)),
                ('nausea', models.FloatField(blank=True, null=True)),
                ('vk_img', models.TextField(blank=True, null=True)),
                ('vk_public_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knowall',
            },
            bases=(models.Model, main.models.ViewCounterModel),
        ),
        migrations.CreateModel(
            name='KnowallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('create_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('update_time', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'knowall_category',
            },
        ),
        migrations.CreateModel(
            name='KnowallGrab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('raw', models.TextField()),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('translate', models.TextField()),
                ('checked', models.IntegerField(blank=True, null=True)),
                ('translate_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'knowall_grab',
            },
        ),
        migrations.AddField(
            model_name='knowall',
            name='knowall_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='knowall.KnowallCategory'),
        ),
    ]
