# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('knowall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowall',
            name='create_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='knowall',
            name='public_time',
            field=unixtimestampfield.fields.UnixTimeStampField(default=1493068531),
        ),
        migrations.AlterField(
            model_name='knowall',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='knowall',
            name='update_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='knowallcategory',
            name='create_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='knowallcategory',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='knowallcategory',
            name='update_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, default=0.0),
        ),
    ]
