# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('knowall', '0002_auto_20170425_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowall',
            name='public_time',
            field=unixtimestampfield.fields.UnixTimeStampField(default=1493068593),
        ),
        migrations.AlterField(
            model_name='knowall',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='knowallcategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
