# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GdzBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('create_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('update_time', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('author', models.CharField(max_length=255)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('properties', models.CharField(blank=True, max_length=255, null=True)),
                ('pagination', models.CharField(blank=True, max_length=255, null=True)),
                ('public_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('lang', models.CharField(blank=True, max_length=255, null=True)),
                ('public', models.BooleanField()),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('vk_img', models.IntegerField(blank=True, null=True)),
                ('vk_public_time', unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True)),
                ('is_promote', models.BooleanField()),
            ],
            options={
                'db_table': 'gdz_book',
            },
            bases=(models.Model, main.models.ViewCounterModel),
        ),
        migrations.CreateModel(
            name='GdzClas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('create_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('update_time', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_promote', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gdz_clas',
            },
        ),
        migrations.CreateModel(
            name='GdzSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('create_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('update_time', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_promote', models.BooleanField()),
                ('gdz_clas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clas_subjects', to='gdz.GdzClas')),
            ],
            options={
                'db_table': 'gdz_subject',
            },
        ),
        migrations.AddField(
            model_name='gdzbook',
            name='gdz_clas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gdz_clas_books', to='gdz.GdzClas'),
        ),
        migrations.AddField(
            model_name='gdzbook',
            name='gdz_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gdz_subject_books', to='gdz.GdzSubject'),
        ),
    ]
