# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdz', '0002_auto_20170425_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdzbook',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gdzclas',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gdzsubject',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
