# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('create_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('update_time', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('public_time', unixtimestampfield.fields.UnixTimeStampField(default=1493058114)),
                ('text', models.TextField()),
                ('length', models.SmallIntegerField()),
                ('nausea', models.FloatField()),
                ('thumbnail_ext', models.CharField(blank=True, max_length=255, null=True)),
                ('public', models.BooleanField()),
                ('vk_img', models.TextField(blank=True, null=True)),
                ('vk_public_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'writing',
            },
            bases=(models.Model, main.models.ViewCounterModel),
        ),
        migrations.CreateModel(
            name='WritingClas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('create_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('update_time', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
            ],
            options={
                'db_table': 'writing_clas',
            },
        ),
        migrations.CreateModel(
            name='WritingSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('uri', models.CharField(max_length=255, unique=True)),
                ('create_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('update_time', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('writing_clas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='writing.WritingClas')),
            ],
            options={
                'db_table': 'writing_subject',
            },
        ),
        migrations.AddField(
            model_name='writing',
            name='clas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='writing.WritingClas'),
        ),
        migrations.AddField(
            model_name='writing',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_writings', to='writing.WritingSubject'),
        ),
    ]
