# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('refresh', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=255)),
                ('code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='BannerCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ads.Banner')),
            ],
            options={
                'db_table': 'banner_code',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('updated_at', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('refresh', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('entity', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='PlaceBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ads.Banner')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ads.Place')),
            ],
            options={
                'db_table': 'place_banner',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='banner',
            field=models.ManyToManyField(through='ads.PlaceBanner', to='ads.Banner', verbose_name='books'),
        ),
    ]
